default_stages: [commit]

repos:

- repo: local
  hooks:
  - id: rustfmt
    name: rustfmt
    entry: rustfmt
    language: system
    types: [rust]

- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort
    stages: [commit]

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3
    stages: [commit]


- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    stages: [commit]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
  - id: mypy

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --preserve-quotes]
  - id: pretty-format-toml
    args: [--autofix]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-toml
  - id: mixed-line-ending
    args: [--fix=lf]
    stages: [commit]

- repo: local
  hooks:
  - id: rustclippy
    name: rustclippy
    entry: cargo clippy --all-targets --all-features -- -Dclippy::all
    pass_filenames: false
    language: system
    types: [rust]
