[[bench]]
name = "bench_fill"
harness = false

[dependencies]
num-traits = "0.2.17"
rayon = {version="1.6.1", optional = true}
thiserror = ">=1.0.51"

[dependencies.serde]
version = "1.0.120"
features = [ "derive",]
optional = true

[dev-dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
serde_json = "1.0.108"
version-sync = "0.9.5"
paste = "1.0.14"
rstest = "0.23.0"

[dev-dependencies.criterion]
version = "0.5.1"
features = [ "html_reports",]

[lib]
bench = false

[package]
name = "ndhistogram"
version = "0.10.0"
authors = [ "David Hadley <davehadley@users.noreply.github.com>",]
edition = "2021"
rust-version = "1.63.0"
license = "MIT OR Apache-2.0"
description = "multi-dimensional histogramming for Rust"
repository = "https://github.com/davehadley/ndhistogram"
readme = "README.md"
keywords = [ "histogram", "statistics", "data", "analysis", "multidimensional",]
categories = [ "science", "mathematics", "data-structures",]

[features]
default = []

[package.metadata.docs.rs]

# have docs.rs document all features
# see: https://docs.rs/about/metadata
all-features = true

