[[bench]]
name = "bench_fill"
harness = false

[dependencies]
num-traits = "0.2.14"

[dependencies.serde]
version = "1.0.120"
features = [ "derive",]
optional = true

[dev-dependencies]
rand = "0.8.0"
rand_distr = "0.4.0"
serde_json = "1.0.61"
version-sync = "0.9.1"
paste = "1.0.4"
rstest = "0.12"

[dev-dependencies.criterion]
version = "0.3.4"
features = [ "html_reports",]

[lib]
bench = false

[package]
name = "ndhistogram"
version = "0.8.0"
authors = [ "David Hadley <davehadley@users.noreply.github.com>",]
edition = "2018"
rust = "1.54.0"
license = "MIT OR Apache-2.0"
description = "multi-dimensional histogramming for Rust"
repository = "https://github.com/davehadley/ndhistogram"
readme = "README.md"
keywords = [ "histogram", "statistics", "data", "analysis", "multidimensional",]
categories = [ "science", "mathematics", "data-structures",]

[features]
default = []