[package]
name = "ndhistogram"
version = "0.4.0"
authors = [ "David Hadley <davehadley@users.noreply.github.com>",]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "multi-dimensional histogramming for Rust"
homepage = "https://github.com/davehadley/rust-hist"
repository = "https://github.com/davehadley/rust-hist"
readme = "README.md"
documentation = "https://docs.rs/ndhistogram"

[dependencies]
num-traits = "0.2.14"

[dev-dependencies]
rand = "0.8.0"
rand_distr = "0.4.0"
serde_json = "1.0.61"

[dependencies.serde]
version = "1.0.120"
features = [ "derive",]
