[package]
name = "ndhistogram"
version = "0.1.0"
authors = [ "David Hadley <davehadley@users.noreply.github.com>",]
edition = "2018"

[dependencies]
num = "0.3"

[dev-dependencies]
itertools = "0.9"
float-cmp = "0.8.0"
