[package]
name = "ndhistogram"
version = "0.1.0"
authors = [ "David Hadley <davehadley@users.noreply.github.com>",]
edition = "2018"

[dependencies]
num-traits = "0.2.14"

[dev-dependencies]
rand = "0.8.0"
rand_distr = "0.4.0"
