name: ci

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]


jobs:
  check:
    name: Check
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: cargo check (default features)
      run: RUSTFLAGS="-D warnings" cargo check
    - name: cargo check (all features)
      run: RUSTFLAGS="-D warnings" cargo check --all-features

  test:
    name: Test Suite
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
    - name: publish dry-run
      working-directory: ./ndhistogram
      run: cargo publish --locked --dry-run

  fmt:
    name: Lints
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - run: rustup component add rustfmt
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - run: rustup component add clippy
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
    - name: cargo doc
      run: RUSTDOCFLAGS="-D warnings" cargo doc
    - name: cargo sync-readme
      run: cargo install cargo-sync-readme && cd ndhistogram && cargo sync-readme --check
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Run pre-commit hooks
      run: |
        pip install pre-commit \
        && pre-commit run --all-files

