name: ci

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]


jobs:
  check:
    name: Check
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: cargo check (default features)
      run: RUSTFLAGS="-D warnings" cargo check
    - name: cargo check (all features)
      run: RUSTFLAGS="-D warnings" cargo check --all-features

  test:
    name: Test Suite
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - name: Run unit/integration tests
      run: cargo test --all-features
    - name: publish dry-run
      working-directory: ./ndhistogram
      run: cargo publish --locked --dry-run

  fmt:
    name: Lints
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt clippy
    - uses: Swatinem/rust-cache@v2
    - name: rustfmt
      run: cargo fmt --all -- --check
    - name: clippy
      run: cargo clippy -- -D warnings
    - name: cargo doc
      run: RUSTDOCFLAGS="-D warnings" cargo doc
    - name: cargo sync-readme
      working-directory: ./ndhistogram
      run: cargo install cargo-sync-readme && cargo sync-readme --check
    - name: Setup python
      uses: actions/setup-python@v4
    - name: Run pre-commit hooks
      run: |
        pip install pre-commit \
        && pre-commit run --all-files

