name: publish

on:
  release:
    types: [created]


jobs:

  test:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: publish --token ${{ secrets.CRATES_TOKEN }}
